"""Create a versioned output-only diagnostic; never mutate the closed V3 source."""
from pathlib import Path
import hashlib,json
p=Path(__file__).resolve().parent
original=p/'crest_seat_search_probe_v3.py'
assert hashlib.sha256(original.read_bytes()).hexdigest()=='85c485e5382adad57e83bc8e3c924e0a9ac3b36dfc896ed77712201baeb02bf9'
source=original.read_text(); changes=[]
def replace(old,new,purpose):
 global source
 assert source.count(old)==1,(purpose,source.count(old))
 source=source.replace(old,new); changes.append({'purpose':purpose,'original':old,'diagnostic':new})
replace('from crest_seat_observer_v3 import CrestSeatDropWindowV3\n', 'from crest_seat_observer_v3 import CrestSeatDropWindowV3\nfrom reverse_brake_v4 import C2ReverseBrake, BrakeSample, _finite_scalar as _brake_finite_scalar\n', 'Use a separate pure robot-yaw brake helper; existing crest observer remains unchanged')
replace('    phases = [("cold_window_hold", .5, 0., 0., control.arm.closed_aperture,\n               control.arm.closed_aperture, True)] + [p for p in supported_phases(control) if p[0] in {\n        "reverse_seat_1", "stop_reverse_seat_1", "start_thread_1", "stop_start_1"}]\n', '    phases = [("cold_window_hold", .5, 0., 0., control.arm.closed_aperture,\n               control.arm.closed_aperture, True)] + [\n        (label, duration+(_COLD_CONTEXT["brake_duration_s"] if label == "stop_reverse_seat_1" else 0.), *rest)\n        for label, duration, *rest in supported_phases(control) if label in {\n        "reverse_seat_1", "stop_reverse_seat_1", "start_thread_1", "stop_start_1"}]\n', 'Include additional real braking interval in immutable maximum phase plan before any native step')
replace('CrestSeatDropWindowV3, cold_table_mean_unavailable,\n','CrestSeatDropWindowV3, cold_table_mean_unavailable, C2ReverseBrake, BrakeSample, _brake_finite_scalar,\n','Bind executed robot-yaw brake definitions in controller function bundle')
replace('                  ArmIK, CrestSeatDropWindowV3):\n','                  ArmIK, CrestSeatDropWindowV3, C2ReverseBrake):\n','Archive full executed robot-yaw brake dependency')
replace('    for phase_index, (label, duration, angle0, angle1, gap0, gap1, axial_float) in enumerate(selected):\n','    reverse_brake = None\n    metadata["robot_yaw_brake"] = {"duration_s": _COLD_CONTEXT["brake_duration_s"],\n        "source_sha256": _COLD_CONTEXT["brake_sha256"],\n        "scope": "Actual measured crest return requests CLOSED robot-yaw deceleration. C2 target-clock continuation uses only the preceding independent scheduled theta/omega/alpha; no object/pitch phase or pose is imposed. Actual native hard guards remain active during braking; original100ms quiet/impulse/90–10 support is required afterwards."}\n    for phase_index, (label, duration, angle0, angle1, gap0, gap1, axial_float) in enumerate(selected):\n','Declare separate braking state/parameters and unchanged native qualification scopes')
replace('        elif label == "start_thread_1":\n','        elif label == "stop_reverse_seat_1":\n            if reverse_brake is None:\n                raise RuntimeError("No preceding independently scheduled reverse clock for braking")\n        elif label == "start_thread_1":\n','Observe original stop bound only after additional real150ms bounded braking maneuver')
replace('            omega = derivative * (angle1 - angle0) / duration\n','            omega = derivative * (angle1 - angle0) / duration\n            alpha = (60*u-180*u*u+120*u*u*u)*(angle1-angle0)/(duration*duration)\n            jerk = (60-360*u+360*u*u)*(angle1-angle0)/(duration*duration*duration)\n            robot_yaw_brake_active = False\n            if label == "stop_reverse_seat_1":\n                brake_sample = reverse_brake.sample((step+1)*model.opt.timestep)\n                theta, omega = brake_sample.theta_rad, brake_sample.omega_rad_s\n                alpha, jerk = brake_sample.alpha_rad_s2, brake_sample.jerk_rad_s3\n                robot_yaw_brake_active = (step+1)*model.opt.timestep < reverse_brake.duration_s-1e-12\n','Replace abrupt angular feedforward step with a C2 command clock and matching derivatives')
replace('                    physically_stopped=label == "stop_reverse_seat_1")\n','                    physically_stopped=(label == "stop_reverse_seat_1" and not robot_yaw_brake_active))\n','Braking cannot count as stopped-direction qualification')
replace('                feedback_phase_completed = True\n', '                feedback_phase_completed = True\n                if label == "reverse_seat_1":\n                    try:\n                        reverse_brake = C2ReverseBrake(theta, omega, alpha,\n                            _COLD_CONTEXT["brake_duration_s"],\n                            minimum_theta_rad=-control.maximum_reverse_angle_rad,\n                            maximum_theta_rad=0., maximum_speed_rad_s=control.reverse_angular_speed_rad_s)\n                    except ValueError as error:\n                        reverse_brake = None\n                        feedback_phase_completed = False\n                        gate = "invalid"\n                        aborted = {"phase": label, "time": float(data.time),\n                            "reason": "Independent C2 robot-yaw braking plan rejected without relaxing bounds",\n                            "brake_validation_error": str(error),\n                            "scheduled_theta_rad": theta, "scheduled_omega_rad_s": omega,\n                            "scheduled_alpha_rad_s2": alpha}\n                    if reverse_brake is not None:\n                        metadata["physical_motion_events"].append({\n                            "event": "Measured crest return requests C2 CLOSED robot-yaw braking",\n                            "time_s": float(data.time), "force_time_s": float(data.time)-model.opt.timestep,\n                            "initial_theta_rad": theta, "initial_omega_rad_s": omega,\n                            "initial_alpha_rad_s2": alpha, "duration_s": reverse_brake.duration_s,\n                            "terminal_theta_rad": reverse_brake.sample(reverse_brake.duration_s).theta_rad,\n                            "scope": "Direction-search deceleration request only; actual original load/quiet windows still unqualified."})\n', 'Freeze only preceding independent scheduled jet; any rejected bounded curve closes orderly with the original last solved row')
replace('"event": "Live physical phase readiness consumed",\n                    "phase": label, "time_s": float(data.time)', '"event": ("Live physical phase readiness consumed" if feedback_phase_completed\n                              else "Live direction request could not form a bounded braking plan"),\n                    "phase": label, "time_s": float(data.time)', 'Do not claim consumed readiness when bounded command planning rejected; preserve failure metadata')
replace('left_angle, cold_table_window_warmup))\n','left_angle, cold_table_window_warmup, robot_yaw_brake_active, alpha, jerk))\n','Retain all original raw fields and add exact actual brake command scalars')
replace('"cold_table_window_warmup")\n','"cold_table_window_warmup", "robot_yaw_brake_active", "desired_independent_angular_acceleration_rad_s2", "desired_independent_angular_jerk_rad_s3")\n','Add matching raw ledger column declarations')
replace('"all_hard_guards_held": hard_guards_held, "cold_table_window_warmup": cold_table_window_warmup,\n','"all_hard_guards_held": hard_guards_held, "cold_table_window_warmup": cold_table_window_warmup,\n                    "robot_yaw_brake_active": robot_yaw_brake_active,\n                    "desired_independent_angular_acceleration_rad_s2": alpha,\n                    "desired_independent_angular_jerk_rad_s3": jerk,\n','Save original native boundary physics together with matching command derivatives')
replace('    parser.add_argument("--prepare-only", action="store_true")\n','    parser.add_argument("--prepare-only", action="store_true")\n    parser.add_argument("--brake-duration", type=float, default=.15)\n','Declare finite physical brake duration in exact CLI')
replace('    args = parser.parse_args()\n','    args = parser.parse_args()\n    if not np.isfinite(args.brake_duration) or args.brake_duration <= 0:\n        raise ValueError("Brake duration must be finite and positive")\n','Validate brake duration before preparing native state')
replace('    source_sha, observer_sha = _sha(__file__), _sha(observer_path)\n','    source_sha, observer_sha = _sha(__file__), _sha(observer_path)\n    brake_path = Path(inspect.getfile(C2ReverseBrake))\n    brake_sha = _sha(brake_path)\n','Bind exact executed new dependency at trial startup')
replace('"controller_source_sha256":source_sha, "crest_observer_source_sha256":observer_sha,\n','"controller_source_sha256":source_sha, "crest_observer_source_sha256":observer_sha,\n        "robot_yaw_brake_source_sha256":brake_sha, "robot_yaw_brake_duration_s":args.brake_duration,\n','Archive exact new command helper and configured duration')
replace('"physical_change":"Replace absolute-settled-depth direction observer with measured-crest-return CLOSED stop request. Require persistent return and original100ms native impulse/angular/axial quiet PLUS original100ms90/10 native weight before first closed forward. Original controller command targets, finite caps and every hard physics/grasp/table/support guard are unchanged.",\n','"physical_change":"Same V3 measured-crest-return observer, original cold input and hard guards. Replace abrupt yaw-stop with explicit C2 CLOSED robot-yaw braking from independently scheduled preceding theta/omega/alpha, then original750ms stop observation bound. Actual persistent return and fresh100ms native impulse/angular/axial quiet PLUS unchanged100ms90/10 native weight are required before first closed forward. No object/pitch/helix drive or state write after initialization.",\n','Truthful limited physical change and no false command-identity claim')
replace('    (args.output/"experimental_observer_source.py").write_bytes(observer_path.read_bytes())\n','    (args.output/"experimental_observer_source.py").write_bytes(observer_path.read_bytes())\n    (args.output/"robot_yaw_brake_source.py").write_bytes(brake_path.read_bytes())\n','Preserve exact full new dependency independent of checkout')
replace('"observer_sha256":observer_sha,"declaration":declaration}\n','"observer_sha256":observer_sha,"declaration":declaration,\n        "brake_sha256":brake_sha, "brake_duration_s":args.brake_duration}\n','Supply only declared command-helper settings to native controller')
replace('"observer_sha256_before":observer_sha,"observer_sha256_after":_sha(observer_path),\n','"observer_sha256_before":observer_sha,"observer_sha256_after":_sha(observer_path),\n        "brake_sha256_before":brake_sha,"brake_sha256_after":_sha(brake_path),\n','Verify dependency unchanged after native closure')
replace('            or closure["parent_input_sha256_after"] != inputs):\n','            or brake_sha != _sha(brake_path)\n            or closure["parent_input_sha256_after"] != inputs):\n','Hard stop on any changed execution dependency')
replace('"cold-crest-return-diagnostic-v3"','"cold-crest-return-c2-brake-diagnostic-v4"','Version the new physical diagnostic')
out=p/'crest_seat_brake_probe_v4.py'; out.write_text(source)
(p/'crest_seat_brake_probe_v4.changes.json').write_text(json.dumps(changes,indent=2)+'\n')
print(json.dumps({'harness_sha256':hashlib.sha256(out.read_bytes()).hexdigest(),'changes':len(changes)}))
